// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqWkYBV-sSFjIIarncy7XlxQTO508J1dQ',
    appId: '1:120650564130:web:d145fd739bf69fb1c4407b',
    messagingSenderId: '120650564130',
    projectId: 'streaming-48b51',
    authDomain: 'streaming-48b51.firebaseapp.com',
    databaseURL: 'https://streaming-48b51-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'streaming-48b51.appspot.com',
    measurementId: 'G-VEJXYGG5MK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6rMROTfcKIlVF8Mo1L2N4A9Y7aj4fLEc',
    appId: '1:120650564130:android:fe284c445661a4e4c4407b',
    messagingSenderId: '120650564130',
    projectId: 'streaming-48b51',
    databaseURL: 'https://streaming-48b51-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'streaming-48b51.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKl5A0N0TS9rKUj4okTLzv71Vyn8htm9k',
    appId: '1:120650564130:ios:e8f1a2ef19a85019c4407b',
    messagingSenderId: '120650564130',
    projectId: 'streaming-48b51',
    databaseURL: 'https://streaming-48b51-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'streaming-48b51.appspot.com',
    iosBundleId: 'com.example.streaming',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKl5A0N0TS9rKUj4okTLzv71Vyn8htm9k',
    appId: '1:120650564130:ios:e8f1a2ef19a85019c4407b',
    messagingSenderId: '120650564130',
    projectId: 'streaming-48b51',
    databaseURL: 'https://streaming-48b51-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'streaming-48b51.appspot.com',
    iosBundleId: 'com.example.streaming',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqWkYBV-sSFjIIarncy7XlxQTO508J1dQ',
    appId: '1:120650564130:web:d701869a6db90bafc4407b',
    messagingSenderId: '120650564130',
    projectId: 'streaming-48b51',
    authDomain: 'streaming-48b51.firebaseapp.com',
    databaseURL: 'https://streaming-48b51-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'streaming-48b51.appspot.com',
    measurementId: 'G-KWM5B1JW9W',
  );

}